apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kubedumbmerch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: registry.daffa.studentdumbways.my.id/finaltask-be-dumbmerch:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: kubedumbmerch
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005
  type: NodePort
