apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: kubedumbmerch
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql
